### ISSUE TITLE
SoundTheAlarm: Alert doesn't show when attacked and you aren't the king

### ISSUE THREAD

**Issue by iPherian** [AlpineSoftworks/bannerlord-mods#1]
Here's a save to demonstrate. An ai lord is about to attack your settlement of Amitatys, but the alert doesn't show.

https://github.com/iPherian/bannerlord-mods/raw/saves/SoundTheAlarm/saves/soundalarm%20attkd.zip

**Comment by AlpineSoftworks** [comment]
Hey there, provided you are the lord of that fief or you are the ruler of the faction, it should announce it to you. If you are in a faction, and another lords fief is attacked, it will NOT notify you, as it is not owned by you.
